version: '3.8'

services:
  php-runtime:
    image: livecodesvip/php-runtime:latest
    container_name: php-runtime
    restart: always
    ports:
      - "5080:80"
      - "5090:8080"
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=fengqing
    volumes:
      - php-runtime_repo:/var/www/repo

volumes:
  php-runtime_repo: